create table item (id integer not null, description varchar(255), image varchar(255), title varchar(255), user_id integer, primary key (id)) engine=InnoDB;
create table item_seq (next_val bigint) engine=InnoDB;
insert into item_seq values ( 1 );
create table trade (id integer not null, statut smallint, offerer_id integer, receiver_id integer, primary key (id)) engine=InnoDB;
create table trade_desired_item (trade_entity_id integer not null, desired_item_id integer not null) engine=InnoDB;
create table trade_offered_items (trade_entity_id integer not null, offered_items_id integer not null) engine=InnoDB;
create table trade_seq (next_val bigint) engine=InnoDB;
insert into trade_seq values ( 1 );
create table user (id integer not null, email varchar(255), location varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table user_seq (next_val bigint) engine=InnoDB;
insert into user_seq values ( 1 );
alter table trade_desired_item add constraint UK_ahy68df0r5hw7idb9dg2vh75a unique (desired_item_id);
alter table trade_offered_items add constraint UK_rsnmio2l2xfjjltaptsog50lm unique (offered_items_id);
alter table item add constraint FKh4epdoqikj4sfedlxcc9dwwnl foreign key (user_id) references user (id);
alter table trade add constraint FK25mqv91n7u9y07gk87xfmi8mg foreign key (offerer_id) references user (id);
alter table trade add constraint FKero4sny1b39c8jfnhg6opru6b foreign key (receiver_id) references user (id);
alter table trade_desired_item add constraint FK8xi7q81llj21b0n9l3ptree3r foreign key (desired_item_id) references item (id);
alter table trade_desired_item add constraint FKn7el0xr8gjadjm6jggutgx7km foreign key (trade_entity_id) references trade (id);
alter table trade_offered_items add constraint FKot30m1tdgrp3sp3qvt1suinay foreign key (offered_items_id) references item (id);
alter table trade_offered_items add constraint FK9644i4r4qe232x1gli3ketgyd foreign key (trade_entity_id) references trade (id);
create table item (id integer not null, description varchar(255), image varchar(255), title varchar(255), user_id integer, primary key (id)) engine=InnoDB;
create table item_seq (next_val bigint) engine=InnoDB;
insert into item_seq values ( 1 );
create table trade (id integer not null, statut smallint, offerer_id integer, receiver_id integer, primary key (id)) engine=InnoDB;
create table trade_desired_item (trade_entity_id integer not null, desired_item_id integer not null) engine=InnoDB;
create table trade_offered_items (trade_entity_id integer not null, offered_items_id integer not null) engine=InnoDB;
create table trade_seq (next_val bigint) engine=InnoDB;
insert into trade_seq values ( 1 );
create table user (id integer not null, email varchar(255), location varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table user_seq (next_val bigint) engine=InnoDB;
insert into user_seq values ( 1 );
alter table trade_desired_item add constraint UK_ahy68df0r5hw7idb9dg2vh75a unique (desired_item_id);
alter table trade_offered_items add constraint UK_rsnmio2l2xfjjltaptsog50lm unique (offered_items_id);
alter table item add constraint FKh4epdoqikj4sfedlxcc9dwwnl foreign key (user_id) references user (id);
alter table trade add constraint FK25mqv91n7u9y07gk87xfmi8mg foreign key (offerer_id) references user (id);
alter table trade add constraint FKero4sny1b39c8jfnhg6opru6b foreign key (receiver_id) references user (id);
alter table trade_desired_item add constraint FK8xi7q81llj21b0n9l3ptree3r foreign key (desired_item_id) references item (id);
alter table trade_desired_item add constraint FKn7el0xr8gjadjm6jggutgx7km foreign key (trade_entity_id) references trade (id);
alter table trade_offered_items add constraint FKot30m1tdgrp3sp3qvt1suinay foreign key (offered_items_id) references item (id);
alter table trade_offered_items add constraint FK9644i4r4qe232x1gli3ketgyd foreign key (trade_entity_id) references trade (id);
create table item (id integer not null, description varchar(255), image varchar(255), title varchar(255), user_id integer, primary key (id)) engine=InnoDB;
create table item_seq (next_val bigint) engine=InnoDB;
insert into item_seq values ( 1 );
create table trade (id integer not null, statut smallint, offerer_id integer, receiver_id integer, primary key (id)) engine=InnoDB;
create table trade_desired_item (trade_entity_id integer not null, desired_item_id integer not null) engine=InnoDB;
create table trade_offered_items (trade_entity_id integer not null, offered_items_id integer not null) engine=InnoDB;
create table trade_seq (next_val bigint) engine=InnoDB;
insert into trade_seq values ( 1 );
create table user (id integer not null, email varchar(255), location varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table user_seq (next_val bigint) engine=InnoDB;
insert into user_seq values ( 1 );
alter table trade_desired_item add constraint UK_ahy68df0r5hw7idb9dg2vh75a unique (desired_item_id);
alter table trade_offered_items add constraint UK_rsnmio2l2xfjjltaptsog50lm unique (offered_items_id);
alter table item add constraint FKh4epdoqikj4sfedlxcc9dwwnl foreign key (user_id) references user (id);
alter table trade add constraint FK25mqv91n7u9y07gk87xfmi8mg foreign key (offerer_id) references user (id);
alter table trade add constraint FKero4sny1b39c8jfnhg6opru6b foreign key (receiver_id) references user (id);
alter table trade_desired_item add constraint FK8xi7q81llj21b0n9l3ptree3r foreign key (desired_item_id) references item (id);
alter table trade_desired_item add constraint FKn7el0xr8gjadjm6jggutgx7km foreign key (trade_entity_id) references trade (id);
alter table trade_offered_items add constraint FKot30m1tdgrp3sp3qvt1suinay foreign key (offered_items_id) references item (id);
alter table trade_offered_items add constraint FK9644i4r4qe232x1gli3ketgyd foreign key (trade_entity_id) references trade (id);
create table item (id integer not null, description varchar(255), image varchar(255), title varchar(255), user_id integer, primary key (id)) engine=InnoDB;
create table item_seq (next_val bigint) engine=InnoDB;
insert into item_seq values ( 1 );
create table trade (id integer not null, statut smallint, offerer_id integer, receiver_id integer, primary key (id)) engine=InnoDB;
create table trade_desired_item (trade_entity_id integer not null, desired_item_id integer not null) engine=InnoDB;
create table trade_offered_items (trade_entity_id integer not null, offered_items_id integer not null) engine=InnoDB;
create table trade_seq (next_val bigint) engine=InnoDB;
insert into trade_seq values ( 1 );
create table user (id integer not null, email varchar(255), location varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table user_seq (next_val bigint) engine=InnoDB;
insert into user_seq values ( 1 );
alter table trade_desired_item add constraint UK_ahy68df0r5hw7idb9dg2vh75a unique (desired_item_id);
alter table trade_offered_items add constraint UK_rsnmio2l2xfjjltaptsog50lm unique (offered_items_id);
alter table item add constraint FKh4epdoqikj4sfedlxcc9dwwnl foreign key (user_id) references user (id);
alter table trade add constraint FK25mqv91n7u9y07gk87xfmi8mg foreign key (offerer_id) references user (id);
alter table trade add constraint FKero4sny1b39c8jfnhg6opru6b foreign key (receiver_id) references user (id);
alter table trade_desired_item add constraint FK8xi7q81llj21b0n9l3ptree3r foreign key (desired_item_id) references item (id);
alter table trade_desired_item add constraint FKn7el0xr8gjadjm6jggutgx7km foreign key (trade_entity_id) references trade (id);
alter table trade_offered_items add constraint FKot30m1tdgrp3sp3qvt1suinay foreign key (offered_items_id) references item (id);
alter table trade_offered_items add constraint FK9644i4r4qe232x1gli3ketgyd foreign key (trade_entity_id) references trade (id);
create table item (id integer not null, description varchar(255), image varchar(255), title varchar(255), user_id integer, primary key (id)) engine=InnoDB;
create table item_seq (next_val bigint) engine=InnoDB;
insert into item_seq values ( 1 );
create table trade (id integer not null, statut smallint, offerer_id integer, receiver_id integer, primary key (id)) engine=InnoDB;
create table trade_desired_item (trade_entity_id integer not null, desired_item_id integer not null) engine=InnoDB;
create table trade_offered_items (trade_entity_id integer not null, offered_items_id integer not null) engine=InnoDB;
create table trade_seq (next_val bigint) engine=InnoDB;
insert into trade_seq values ( 1 );
create table user (id integer not null, email varchar(255), location varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table user_seq (next_val bigint) engine=InnoDB;
insert into user_seq values ( 1 );
alter table trade_desired_item add constraint UK_ahy68df0r5hw7idb9dg2vh75a unique (desired_item_id);
alter table trade_offered_items add constraint UK_rsnmio2l2xfjjltaptsog50lm unique (offered_items_id);
alter table item add constraint FKh4epdoqikj4sfedlxcc9dwwnl foreign key (user_id) references user (id);
alter table trade add constraint FK25mqv91n7u9y07gk87xfmi8mg foreign key (offerer_id) references user (id);
alter table trade add constraint FKero4sny1b39c8jfnhg6opru6b foreign key (receiver_id) references user (id);
alter table trade_desired_item add constraint FK8xi7q81llj21b0n9l3ptree3r foreign key (desired_item_id) references item (id);
alter table trade_desired_item add constraint FKn7el0xr8gjadjm6jggutgx7km foreign key (trade_entity_id) references trade (id);
alter table trade_offered_items add constraint FKot30m1tdgrp3sp3qvt1suinay foreign key (offered_items_id) references item (id);
alter table trade_offered_items add constraint FK9644i4r4qe232x1gli3ketgyd foreign key (trade_entity_id) references trade (id);
create table item (id integer not null, description varchar(255), image varchar(255), title varchar(255), user_id integer, primary key (id)) engine=InnoDB;
create table item_seq (next_val bigint) engine=InnoDB;
insert into item_seq values ( 1 );
create table trade (id integer not null, statut smallint, offerer_id integer, receiver_id integer, primary key (id)) engine=InnoDB;
create table trade_desired_item (trade_entity_id integer not null, desired_item_id integer not null) engine=InnoDB;
create table trade_offered_items (trade_entity_id integer not null, offered_items_id integer not null) engine=InnoDB;
create table trade_seq (next_val bigint) engine=InnoDB;
insert into trade_seq values ( 1 );
create table user (id integer not null, email varchar(255), location varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table user_seq (next_val bigint) engine=InnoDB;
insert into user_seq values ( 1 );
alter table trade_desired_item add constraint UK_ahy68df0r5hw7idb9dg2vh75a unique (desired_item_id);
alter table trade_offered_items add constraint UK_rsnmio2l2xfjjltaptsog50lm unique (offered_items_id);
alter table item add constraint FKh4epdoqikj4sfedlxcc9dwwnl foreign key (user_id) references user (id);
alter table trade add constraint FK25mqv91n7u9y07gk87xfmi8mg foreign key (offerer_id) references user (id);
alter table trade add constraint FKero4sny1b39c8jfnhg6opru6b foreign key (receiver_id) references user (id);
alter table trade_desired_item add constraint FK8xi7q81llj21b0n9l3ptree3r foreign key (desired_item_id) references item (id);
alter table trade_desired_item add constraint FKn7el0xr8gjadjm6jggutgx7km foreign key (trade_entity_id) references trade (id);
alter table trade_offered_items add constraint FKot30m1tdgrp3sp3qvt1suinay foreign key (offered_items_id) references item (id);
alter table trade_offered_items add constraint FK9644i4r4qe232x1gli3ketgyd foreign key (trade_entity_id) references trade (id);
